// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { config as dotenvConfig } from "dotenv";
import { defineConfig } from "prisma/config";

// load .env explicitly
dotenvConfig();

if (!process.env.DATABASE_URL) {
  throw new Error(
    "DATABASE_URL not found. Ensure .env in project root contains DATABASE_URL"
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI requires a top-level `url` here for commands like `db push`.
    url: process.env.DATABASE_URL,
  },
});
